# Generated by Django 4.0.4 on 2022-05-23 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('authentication', '0003_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFootballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('footballer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.footballer')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='footballers',
            field=models.ManyToManyField(through='authentication.UserFootballer', to='stock.footballer'),
        ),
        migrations.AddField(
            model_name='user',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.gameweek'),
        ),
        migrations.AddField(
            model_name='userfootballer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
