# Generated by Django 4.0.4 on 2022-05-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userfootballer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfootballer',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
