# Generated by Django 4.0.4 on 2022-05-30 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_footballer_price_dynamic'),
        ('authentication', '0008_userfootballer_trade_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('footballer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.footballer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.gameweek')),
            ],
            options={
                'unique_together': {('user', 'footballer', 'week')},
            },
        ),
    ]
