# Generated by Django 4.0.4 on 2022-06-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_usertradelog_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradelog',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
