# Generated by Django 4.0.4 on 2022-06-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_gameresultslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresultslog',
            name='game_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='game_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
