# Generated by Django 4.0.4 on 2022-06-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_gameresultslog_game_number_user_game_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
