# Generated by Django 4.0.4 on 2022-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballerweeksdata',
            name='hix',
            field=models.DecimalField(decimal_places=2, default=23.15, max_digits=10),
            preserve_default=False,
        ),
    ]
