# Generated by Django 4.0.4 on 2022-05-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_footballerposition_footballerteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='price_dynamic',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
