# Generated by Django 4.0.4 on 2022-06-06 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_footballer_price_dynamic'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekIndexModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.gameweek')),
            ],
        ),
    ]
