version: '3.7'

services:
  backend:
    container_name: backend
    build: 
      dockerfile: ./Dockerfile.dev
      context: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - $PORT:$PORT

  db:
    image: postgres
    container_name: heroex-db
    volumes:
      - ./data/:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
