version: '3.7'

services:
  backend:
    container_name: backend
    build: 
      dockerfile: ./Dockerfile.prod
      context: .
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/authentication/static/js
    env_file:
      - .env
    ports:
      - 8000:8000
