FROM python:3.8

RUN apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs

WORKDIR /app/

COPY ./backend /app/
COPY ./frontend ./frontend

WORKDIR /app/frontend/
RUN npm i
RUN BUILD_PATH='../server/templates' npm run build
WORKDIR /app/
RUN pip install poetry 
RUN poetry export -o requirements.txt
RUN pip install -r requirements.txt

RUN mkdir staticfiles

EXPOSE $PORT

WORKDIR /app/

RUN chmod +x ./entrypoint.sh
ENTRYPOINT ./entrypoint.sh
