version: '3.7'

services:
  ui:
    container_name: ui
    build:
      dockerfile: Dockerfile.ui
      context: ./frontend/
    volumes:
      - ./frontend/:/app/
    depends_on:
      - web
    env_file:
      - .env
    ports:
      - 3000:3000


  web:
    container_name: web
    build: 
      dockerfile: Dockerfile.web
      context: ./backend/
    volumes:
      - ./backend/:/app/
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000

  db:
    image: postgres
    container_name: heroex-db
    volumes:
      - ./data/:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
