FROM python:3.8

RUN apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs

WORKDIR /app/

COPY ./backend /app/
COPY ./frontend ./frontend

WORKDIR /app/frontend/
RUN npm i
RUN npm run build
WORKDIR /app/
RUN cp ./frontend/dist/main.js ./authentication/static/js/main.js

RUN pip install poetry 
RUN poetry install

RUN mkdir staticfiles

EXPOSE $PORT

WORKDIR /app/

RUN chmod +x ./entrypoint.sh
ENTRYPOINT ./entrypoint.sh
